spring:
  application:
    name: StudentInfoDb

  datasource:
    url: jdbc:mysql://localhost:3306/StudentSystem
    username: root
    password: sangita@2845

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
